CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    surname VARCHAR(50)                                    NOT NULL,
    name VARCHAR(50)                                       NOT NULL,
    patronymic VARCHAR(50)                                 NOT NULL,
    birthdate TIMESTAMP WITHOUT TIME ZONE                  NOT NULL,
    email VARCHAR(50) UNIQUE                               NOT NULL,
    tel_number BIGINT UNIQUE                               NOT NULL,
    role VARCHAR(20)                                       NOT NULL,
    filename VARCHAR(300)
    );